// wordData.js
const wordData = [
  { "word": "その", "type": "連体詞" },
  { "word": "あの", "type": "連体詞" },
  { "word": "この", "type": "連体詞" },
  { "word": "大きな", "type": "連体詞" },
  { "word": "小さな", "type": "連体詞" },
  { "word": "あらゆる", "type": "連体詞" },
  { "word": "たいした", "type": "連体詞" },
  { "word": "どの", "type": "連体詞" },
  { "word": "とても", "type": "副詞" },
  { "word": "ざーざーと", "type": "副詞" },
  { "word": "かなり", "type": "副詞" },
  { "word": "ゆっくり", "type": "副詞" },
  { "word": "あまり", "type": "副詞" },
  { "word": "静かだ", "type": "形容動詞" },
  { "word": "元気だ", "type": "形容動詞" },
  { "word": "簡単だ", "type": "形容動詞" },
  { "word": "きれいだ", "type": "形容動詞" },
  { "word": "大切だ", "type": "形容動詞" },
  { "word": "大きい", "type": "形容詞" },
  { "word": "楽しい", "type": "形容詞" },
  { "word": "青い", "type": "形容詞" },
  { "word": "赤い", "type": "形容詞" },
  { "word": "寒い", "type": "形容詞" },
  { "word": "白い", "type": "形容詞" },
  { "word": "黒い", "type": "形容詞" },
  { "word": "暑い", "type": "形容詞" },
  { "word": "涼しい", "type": "形容詞" },
  { "word": "嬉しい", "type": "形容詞" },
  { "word": "悲しい", "type": "形容詞" },
  { "word": "速い", "type": "形容詞" },
  { "word": "遅い", "type": "形容詞" },
  { "word": "すごい", "type": "形容詞" },
  { "word": "行く", "type": "動詞" },
  { "word": "見る", "type": "動詞" },
  { "word": "遊ぶ", "type": "動詞" },
  { "word": "飛ぶ", "type": "動詞" },
  { "word": "読む", "type": "動詞" },
  { "word": "泳ぐ", "type": "動詞" },
  { "word": "怒る", "type": "動詞" },
  { "word": "走る", "type": "動詞" },
  { "word": "食べる", "type": "動詞" },
  { "word": "笑う", "type": "動詞" },
  { "word": "する", "type": "動詞" },
  { "word": "来る", "type": "動詞" },
  { "word": "なる", "type": "動詞" },
]



export default wordData; // エクスポートは1回だけ
