export default [
  // ===== 名詞 =====
  { sentence: "川の流れが美しい。", word: "流れ", type: "名詞" },
  { sentence: "春の訪れを感じた。", word: "訪れ", type: "名詞" },
  { sentence: "彼の努力が実を結んだ。", word: "努力", type: "名詞" },
  { sentence: "今日の天気は晴れだ。", word: "天気", type: "名詞" },
  { sentence: "山の頂上から景色を眺めた。", word: "頂上", type: "名詞" },
  { sentence: "毎朝の散歩が健康に良い。", word: "散歩", type: "名詞" },
  { sentence: "試合の結果に全員が驚いた。", word: "結果", type: "名詞" },
  { sentence: "読書は知識を増やす。", word: "読書", type: "名詞" },
  { sentence: "彼女の笑顔が素敵だ。", word: "笑顔", type: "名詞" },
  { sentence: "毎朝の歩きが体に良い。", word: "歩き", type: "名詞" },
  { sentence: "音楽の響きが心に残る。", word: "響き", type: "名詞" },
  { sentence: "木々の揺れが心地よい。", word: "揺れ", type: "名詞" },

  // ===== 動詞 =====
  { sentence: "彼は公園を歩きます。", word: "歩き", type: "動詞" },
  { sentence: "川が静かに流れている。", word: "流れ", type: "動詞" },
  { sentence: "花が美しく咲いた。", word: "咲い", type: "動詞" },
  { sentence: "彼女は毎日泳ぐ。", word: "泳ぐ", type: "動詞" },
  { sentence: "空に星が輝いている。", word: "輝い", type: "動詞" },
  { sentence: "図書館で本を読む。", word: "読む", type: "動詞" },
  { sentence: "彼女は歌を歌っている。", word: "歌っ", type: "動詞" },
  { sentence: "彼は友達と話して帰った。", word: "話し", type: "動詞" },
  { sentence: "犬が庭を走り回る。", word: "走り", type: "動詞" },
  { sentence: "木が強い風で揺れた。", word: "揺れ", type: "動詞" },

  // ===== 形容詞 =====
  { sentence: "花が美しく咲き誇る。", word: "美しく", type: "形容詞" },
  { sentence: "この山道はとても険しい。", word: "険しい", type: "形容詞" },
  { sentence: "彼の声が大きく響いた。", word: "大きく", type: "形容詞" },
  { sentence: "赤い夕日が沈んでいく。", word: "赤い", type: "形容詞" },
  { sentence: "この問題は難しくて困った。", word: "難しく", type: "形容詞" },
  { sentence: "財布にお金がない。", word: "ない", type: "形容詞" },
  { sentence: "今日は楽しく過ごした。", word: "楽しく", type: "形容詞" },
  { sentence: "彼の部屋はいつも汚い。", word: "汚い", type: "形容詞" },
  { sentence: "冬の朝は寒く感じる。", word: "寒く", type: "形容詞" },
  { sentence: "深い海の底に何があるのか。", word: "深い", type: "形容詞" },

  // ===== 形容動詞 =====
  { sentence: "静かに勉強する。", word: "静かに", type: "形容動詞" },
  { sentence: "彼女は元気な人だ。", word: "元気な", type: "形容動詞" },
  { sentence: "街がにぎやかだ。", word: "にぎやかだ", type: "形容動詞" },
  { sentence: "彼女は親切に教えてくれた。", word: "親切に", type: "形容動詞" },
  { sentence: "このケーキは上品な味がする。", word: "上品な", type: "形容動詞" },
  { sentence: "彼の態度が不思議だ。", word: "不思議だ", type: "形容動詞" },
  { sentence: "昨日は特別な日だった。", word: "特別な", type: "形容動詞" },
  { sentence: "彼女は丁寧に挨拶した。", word: "丁寧に", type: "形容動詞" },
  { sentence: "部屋が清潔だ。", word: "清潔だ", type: "形容動詞" },
  { sentence: "素直に謝ることが大切だ。", word: "素直に", type: "形容動詞" },

  // ===== 副詞 =====
  { sentence: "彼はとても速く走った。", word: "とても", type: "副詞" },
  { sentence: "彼女はゆっくり歩いた。", word: "ゆっくり", type: "副詞" },
  { sentence: "もっと頑張ればよかった。", word: "もっと", type: "副詞" },
  { sentence: "彼はたくさん本を読む。", word: "たくさん", type: "副詞" },
  { sentence: "よく考えてから答える。", word: "よく", type: "副詞" },
  { sentence: "すぐに返事をしてください。", word: "すぐに", type: "副詞" },
  { sentence: "かなり疲れたので休んだ。", word: "かなり", type: "副詞" },
  { sentence: "もうすぐ夏休みが始まる。", word: "もうすぐ", type: "副詞" },
  { sentence: "まだ宿題が終わっていない。", word: "まだ", type: "副詞" },
  { sentence: "きっと彼は来るだろう。", word: "きっと", type: "副詞" },

  // ===== 助詞 =====
  { sentence: "私は学校に行く。", word: "は", type: "助詞" },
  { sentence: "彼が先生に話した。", word: "が", type: "助詞" },
  { sentence: "学校から走って帰った。", word: "から", type: "助詞" },
  { sentence: "図書館まで歩いた。", word: "まで", type: "助詞" },
  { sentence: "本だけが机にある。", word: "だけ", type: "助詞" },
  { sentence: "友達さえいれば良い。", word: "さえ", type: "助詞" },
  { sentence: "公園で遊んでいる。", word: "で", type: "助詞" },
  { sentence: "兄と映画を見た。", word: "と", type: "助詞" },
  { sentence: "雨なので傘を持った。", word: "ので", type: "助詞" },
  { sentence: "疲れながらも完走した。", word: "ながら", type: "助詞" },

  // ===== 助動詞 =====
  { sentence: "今日は食べない。", word: "ない", type: "助動詞" },
  { sentence: "彼は医者だ。", word: "だ", type: "助動詞" },
  { sentence: "明日は晴れそうだ。", word: "そうだ", type: "助動詞" },
  { sentence: "彼は医者らしい。", word: "らしい", type: "助動詞" },
  { sentence: "雨が降るようだ。", word: "ようだ", type: "助動詞" },
  { sentence: "昨日は公園を走った。", word: "た", type: "助動詞" },
  { sentence: "もっと読みたい。", word: "たい", type: "助動詞" },
  { sentence: "先生に褒められた。", word: "られ", type: "助動詞" },
  { sentence: "弟に部屋を掃除させた。", word: "させ", type: "助動詞" },
  { sentence: "おそらく明日は来るまい。", word: "まい", type: "助動詞" },

  // ===== 接続詞 =====
  { sentence: "しかし彼は来なかった。", word: "しかし", type: "接続詞" },
  { sentence: "でも諦めたくない。", word: "でも", type: "接続詞" },
  { sentence: "だから勉強が大切だ。", word: "だから", type: "接続詞" },
  { sentence: "そして花が咲いた。", word: "そして", type: "接続詞" },
  { sentence: "または電話をください。", word: "または", type: "接続詞" },
  { sentence: "つまり彼が犯人だ。", word: "つまり", type: "接続詞" },
  { sentence: "ところが結果は違った。", word: "ところが", type: "接続詞" },
  { sentence: "なぜなら努力したからだ。", word: "なぜなら", type: "接続詞" },
  { sentence: "したがって答えは三だ。", word: "したがって", type: "接続詞" },
  { sentence: "けれども楽しかった。", word: "けれども", type: "接続詞" },

  // ===== 感動詞 =====
  { sentence: "ああ、なんと美しい。", word: "ああ", type: "感動詞" },
  { sentence: "えっ、本当に？", word: "えっ", type: "感動詞" },
  { sentence: "よし、頑張るぞ！", word: "よし", type: "感動詞" },
  { sentence: "さあ、始めよう。", word: "さあ", type: "感動詞" },
  { sentence: "まあ、そうですか。", word: "まあ", type: "感動詞" },
  { sentence: "はい、わかりました。", word: "はい", type: "感動詞" },
  { sentence: "おい、ちょっと待て！", word: "おい", type: "感動詞" },
  { sentence: "ねえ、聞いてよ。", word: "ねえ", type: "感動詞" },

  // ===== 連体詞 =====
  { sentence: "この本はとても面白い。", word: "この", type: "連体詞" },
  { sentence: "その話は嘘だった。", word: "その", type: "連体詞" },
  { sentence: "あの山が富士山だ。", word: "あの", type: "連体詞" },
  { sentence: "どの道を行けばいい？", word: "どの", type: "連体詞" },
  { sentence: "ある日、彼は突然来た。", word: "ある", type: "連体詞" },
  { sentence: "いわゆる天才というやつだ。", word: "いわゆる", type: "連体詞" },
  { sentence: "たいした問題でもない。", word: "たいした", type: "連体詞" },
  { sentence: "おかしな話だと思った。", word: "おかしな", type: "連体詞" },
  { sentence: "大きな声で返事をした。", word: "大きな", type: "連体詞" },
  { sentence: "ほんの少しだけ食べた。", word: "ほんの", type: "連体詞" },
];
