// wordData.js
const wordData = [
  { word: "サケ", type: "魚類" },
  { word: "マグロ", type: "魚類" },
  { word: "タイ", type: "魚類" },
  { word: "イワシ", type: "魚類" },
  { word: "サバ", type: "魚類" },
  { word: "アジ", type: "魚類" },
  { word: "キンメダイ", type: "魚類" },
  { word: "メダカ", type: "魚類" },
  { word: "ブリ", type: "魚類" },
  { word: "ヒラメ", type: "魚類" },
  { word: "カレイ", type: "魚類" },
  { word: "アナゴ", type: "魚類" },
  { word: "ニジマス", type: "魚類" },
  { word: "タツノオトシゴ", type: "魚類" },

  { word: "カエル", type: "両生類" },
  { word: "イモリ", type: "両生類" },
  { word: "オオサンショウウオ", type: "両生類" },
  { word: "ミドリガエル", type: "両生類" },
  { word: "アカガエル", type: "両生類" },
  { word: "ウーパールーパー", type: "両生類" },

  { word: "トカゲ", type: "ハチュウ類" },
  { word: "ヘビ", type: "ハチュウ類" },
  { word: "カメ", type: "ハチュウ類" },
  { word: "ワニ", type: "ハチュウ類" },
  { word: "イグアナ", type: "ハチュウ類" },
  { word: "ヤモリ", type: "ハチュウ類" },
  { word: "コブラ", type: "ハチュウ類" },
  { word: "ウミガメ", type: "ハチュウ類" },
  { word: "リクガメ", type: "ハチュウ類" },

  { word: "ハト", type: "鳥類" },
  { word: "スズメ", type: "鳥類" },
  { word: "ツバメ", type: "鳥類" },
  { word: "カラス", type: "鳥類" },
  { word: "ワシ", type: "鳥類" },
  { word: "タカ", type: "鳥類" },
  { word: "フクロウ", type: "鳥類" },
  { word: "シジュウカラ", type: "鳥類" },
  { word: "キジ", type: "鳥類" },
  { word: "ツル", type: "鳥類" },
  { word: "ニワトリ", type: "鳥類" },
  { word: "ペンギン", type: "鳥類" },

  { word: "ネコ", type: "ホニュウ類" },
  { word: "ウサギ", type: "ホニュウ類" },
  { word: "イヌ", type: "ホニュウ類" },
  { word: "ネズミ", type: "ホニュウ類" },
  { word: "クマ", type: "ホニュウ類" },
  { word: "サル", type: "ホニュウ類" },
  { word: "ウシ", type: "ホニュウ類" },
  { word: "ブタ", type: "ホニュウ類" },
  { word: "ライオン", type: "ホニュウ類" },
  { word: "キリン", type: "ホニュウ類" },
  { word: "コウモリ", type: "ホニュウ類" },
  { word: "カワウソ", type: "ホニュウ類" },
  { word: "イルカ", type: "ホニュウ類" },
  { word: "クジラ", type: "ホニュウ類" },
];

export default wordData; // エクスポートは1回だけ

