const wordData = [

  // ==================
  // 基本動詞
  // ==================
  { word: "go",       type: "原形",    category: "基本動詞", meaning: "行く",       base: "go" },
  { word: "went",     type: "過去形",   category: "基本動詞", meaning: "行く",       base: "go" },
  { word: "gone",     type: "過去分詞",  category: "基本動詞", meaning: "行く",       base: "go" },
  { word: "see",      type: "原形",    category: "基本動詞", meaning: "見る",       base: "see" },
  { word: "saw",      type: "過去形",   category: "基本動詞", meaning: "見る",       base: "see" },
  { word: "seen",     type: "過去分詞",  category: "基本動詞", meaning: "見る",       base: "see" },
  { word: "give",     type: "原形",    category: "基本動詞", meaning: "あげる",      base: "give" },
  { word: "gave",     type: "過去形",   category: "基本動詞", meaning: "あげる",      base: "give" },
  { word: "given",    type: "過去分詞",  category: "基本動詞", meaning: "あげる",      base: "give" },
  { word: "take",     type: "原形",    category: "基本動詞", meaning: "取る",       base: "take" },
  { word: "took",     type: "過去形",   category: "基本動詞", meaning: "取る",       base: "take" },
  { word: "taken",    type: "過去分詞",  category: "基本動詞", meaning: "取る",       base: "take" },
  { word: "do",       type: "原形",    category: "基本動詞", meaning: "する",       base: "do" },
  { word: "did",      type: "過去形",   category: "基本動詞", meaning: "する",       base: "do" },
  { word: "done",     type: "過去分詞",  category: "基本動詞", meaning: "する",       base: "do" },
  { word: "write",    type: "原形",    category: "基本動詞", meaning: "書く",       base: "write" },
  { word: "wrote",    type: "過去形",   category: "基本動詞", meaning: "書く",       base: "write" },
  { word: "written",  type: "過去分詞",  category: "基本動詞", meaning: "書く",       base: "write" },
  { word: "eat",      type: "原形",    category: "基本動詞", meaning: "食べる",      base: "eat" },
  { word: "ate",      type: "過去形",   category: "基本動詞", meaning: "食べる",      base: "eat" },
  { word: "eaten",    type: "過去分詞",  category: "基本動詞", meaning: "食べる",      base: "eat" },
  { word: "speak",    type: "原形",    category: "基本動詞", meaning: "話す",       base: "speak" },
  { word: "spoke",    type: "過去形",   category: "基本動詞", meaning: "話す",       base: "speak" },
  { word: "spoken",   type: "過去分詞",  category: "基本動詞", meaning: "話す",       base: "speak" },
  { word: "break",    type: "原形",    category: "基本動詞", meaning: "壊す",       base: "break" },
  { word: "broke",    type: "過去形",   category: "基本動詞", meaning: "壊す",       base: "break" },
  { word: "broken",   type: "過去分詞",  category: "基本動詞", meaning: "壊す",       base: "break" },
  { word: "ride",     type: "原形",    category: "基本動詞", meaning: "乗る",       base: "ride" },
  { word: "rode",     type: "過去形",   category: "基本動詞", meaning: "乗る",       base: "ride" },
  { word: "ridden",   type: "過去分詞",  category: "基本動詞", meaning: "乗る",       base: "ride" },

  // ==================
  // i→a→u 型
  // ==================
  { word: "sing",     type: "原形",    category: "i→a→u型", meaning: "歌う",       base: "sing" },
  { word: "sang",     type: "過去形",   category: "i→a→u型", meaning: "歌う",       base: "sing" },
  { word: "sung",     type: "過去分詞",  category: "i→a→u型", meaning: "歌う",       base: "sing" },
  { word: "begin",    type: "原形",    category: "i→a→u型", meaning: "始める",      base: "begin" },
  { word: "began",    type: "過去形",   category: "i→a→u型", meaning: "始める",      base: "begin" },
  { word: "begun",    type: "過去分詞",  category: "i→a→u型", meaning: "始める",      base: "begin" },
  { word: "swim",     type: "原形",    category: "i→a→u型", meaning: "泳ぐ",       base: "swim" },
  { word: "swam",     type: "過去形",   category: "i→a→u型", meaning: "泳ぐ",       base: "swim" },
  { word: "swum",     type: "過去分詞",  category: "i→a→u型", meaning: "泳ぐ",       base: "swim" },
  { word: "ring",     type: "原形",    category: "i→a→u型", meaning: "鳴らす",      base: "ring" },
  { word: "rang",     type: "過去形",   category: "i→a→u型", meaning: "鳴らす",      base: "ring" },
  { word: "rung",     type: "過去分詞",  category: "i→a→u型", meaning: "鳴らす",      base: "ring" },
  { word: "drink",    type: "原形",    category: "i→a→u型", meaning: "飲む",       base: "drink" },
  { word: "drank",    type: "過去形",   category: "i→a→u型", meaning: "飲む",       base: "drink" },
  { word: "drunk",    type: "過去分詞",  category: "i→a→u型", meaning: "飲む",       base: "drink" },
  { word: "sink",     type: "原形",    category: "i→a→u型", meaning: "沈む",       base: "sink" },
  { word: "sank",     type: "過去形",   category: "i→a→u型", meaning: "沈む",       base: "sink" },
  { word: "sunk",     type: "過去分詞",  category: "i→a→u型", meaning: "沈む",       base: "sink" },
  { word: "spring",   type: "原形",    category: "i→a→u型", meaning: "跳ぶ",       base: "spring" },
  { word: "sprang",   type: "過去形",   category: "i→a→u型", meaning: "跳ぶ",       base: "spring" },
  { word: "sprung",   type: "過去分詞",  category: "i→a→u型", meaning: "跳ぶ",       base: "spring" },
  { word: "shrink",   type: "原形",    category: "i→a→u型", meaning: "縮む",       base: "shrink" },
  { word: "shrank",   type: "過去形",   category: "i→a→u型", meaning: "縮む",       base: "shrink" },
  { word: "shrunk",   type: "過去分詞",  category: "i→a→u型", meaning: "縮む",       base: "shrink" },

  // ==================
  // -ew / -own 型
  // ==================
  { word: "grow",     type: "原形",    category: "-ew型",   meaning: "育つ",       base: "grow" },
  { word: "grew",     type: "過去形",   category: "-ew型",   meaning: "育つ",       base: "grow" },
  { word: "grown",    type: "過去分詞",  category: "-ew型",   meaning: "育つ",       base: "grow" },
  { word: "throw",    type: "原形",    category: "-ew型",   meaning: "投げる",      base: "throw" },
  { word: "threw",    type: "過去形",   category: "-ew型",   meaning: "投げる",      base: "throw" },
  { word: "thrown",   type: "過去分詞",  category: "-ew型",   meaning: "投げる",      base: "throw" },
  { word: "blow",     type: "原形",    category: "-ew型",   meaning: "吹く",       base: "blow" },
  { word: "blew",     type: "過去形",   category: "-ew型",   meaning: "吹く",       base: "blow" },
  { word: "blown",    type: "過去分詞",  category: "-ew型",   meaning: "吹く",       base: "blow" },
  { word: "fly",      type: "原形",    category: "-ew型",   meaning: "飛ぶ",       base: "fly" },
  { word: "flew",     type: "過去形",   category: "-ew型",   meaning: "飛ぶ",       base: "fly" },
  { word: "flown",    type: "過去分詞",  category: "-ew型",   meaning: "飛ぶ",       base: "fly" },
  { word: "draw",     type: "原形",    category: "-ew型",   meaning: "描く",       base: "draw" },
  { word: "drew",     type: "過去形",   category: "-ew型",   meaning: "描く",       base: "draw" },
  { word: "drawn",    type: "過去分詞",  category: "-ew型",   meaning: "描く",       base: "draw" },
  { word: "know",     type: "原形",    category: "-ew型",   meaning: "知る",       base: "know" },
  { word: "knew",     type: "過去形",   category: "-ew型",   meaning: "知る",       base: "know" },
  { word: "known",    type: "過去分詞",  category: "-ew型",   meaning: "知る",       base: "know" },

  // ==================
  // 受験頻出
  // ==================
  { word: "fall",      type: "原形",    category: "受験頻出", meaning: "落ちる",      base: "fall" },
  { word: "fell",      type: "過去形",   category: "受験頻出", meaning: "落ちる",      base: "fall" },
  { word: "fallen",    type: "過去分詞",  category: "受験頻出", meaning: "落ちる",      base: "fall" },
  { word: "forget",    type: "原形",    category: "受験頻出", meaning: "忘れる",      base: "forget" },
  { word: "forgot",    type: "過去形",   category: "受験頻出", meaning: "忘れる",      base: "forget" },
  { word: "forgotten", type: "過去分詞",  category: "受験頻出", meaning: "忘れる",      base: "forget" },
  { word: "steal",     type: "原形",    category: "受験頻出", meaning: "盗む",       base: "steal" },
  { word: "stole",     type: "過去形",   category: "受験頻出", meaning: "盗む",       base: "steal" },
  { word: "stolen",    type: "過去分詞",  category: "受験頻出", meaning: "盗む",       base: "steal" },
  { word: "choose",    type: "原形",    category: "受験頻出", meaning: "選ぶ",       base: "choose" },
  { word: "chose",     type: "過去形",   category: "受験頻出", meaning: "選ぶ",       base: "choose" },
  { word: "chosen",    type: "過去分詞",  category: "受験頻出", meaning: "選ぶ",       base: "choose" },
  { word: "wear",      type: "原形",    category: "受験頻出", meaning: "着る",       base: "wear" },
  { word: "wore",      type: "過去形",   category: "受験頻出", meaning: "着る",       base: "wear" },
  { word: "worn",      type: "過去分詞",  category: "受験頻出", meaning: "着る",       base: "wear" },
  { word: "hide",      type: "原形",    category: "受験頻出", meaning: "隠す",       base: "hide" },
  { word: "hid",       type: "過去形",   category: "受験頻出", meaning: "隠す",       base: "hide" },
  { word: "hidden",    type: "過去分詞",  category: "受験頻出", meaning: "隠す",       base: "hide" },
  { word: "wake",      type: "原形",    category: "受験頻出", meaning: "起きる",      base: "wake" },
  { word: "woke",      type: "過去形",   category: "受験頻出", meaning: "起きる",      base: "wake" },
  { word: "woken",     type: "過去分詞",  category: "受験頻出", meaning: "起きる",      base: "wake" },
  { word: "bite",      type: "原形",    category: "受験頻出", meaning: "かむ",       base: "bite" },
  { word: "bit",       type: "過去形",   category: "受験頻出", meaning: "かむ",       base: "bite" },
  { word: "bitten",    type: "過去分詞",  category: "受験頻出", meaning: "かむ",       base: "bite" },
  { word: "drive",     type: "原形",    category: "受験頻出", meaning: "運転する",    base: "drive" },
  { word: "drove",     type: "過去形",   category: "受験頻出", meaning: "運転する",    base: "drive" },
  { word: "driven",    type: "過去分詞",  category: "受験頻出", meaning: "運転する",    base: "drive" },
  { word: "shake",     type: "原形",    category: "受験頻出", meaning: "振る",       base: "shake" },
  { word: "shook",     type: "過去形",   category: "受験頻出", meaning: "振る",       base: "shake" },
  { word: "shaken",    type: "過去分詞",  category: "受験頻出", meaning: "振る",       base: "shake" },
];

export default wordData;
