//ここのファイルは分類させたい単語(word)と、その分類(type)を下の例に従って入力
// wordData.js
const wordData = [
  { "word": "豚肉", "type": "1群" },
  { "word": "牛乳", "type": "2群" },
  { "word": "にんじん", "type": "3群" },
  { "word": "りんご", "type": "4群" },
  { "word": "ごはん", "type": "5群" },
  { "word": "バター", "type": "6群" },
  { "word": "鶏肉", "type": "1群" },
  { "word": "チーズ", "type": "2群" },
  { "word": "ピーマン", "type": "3群" },
  { "word": "バナナ", "type": "4群" },
  { "word": "食パン", "type": "5群" },
  { "word": "アーモンド", "type": "6群" },
  { "word": "魚", "type": "1群" },
  { "word": "ヨーグルト", "type": "2群" },
  { "word": "かぼちゃ", "type": "3群" },
  { "word": "しいたけ", "type": "4群" },
  { "word": "じゃがいも", "type": "5群" },
  { "word": "くるみ", "type": "6群" },
  { "word": "牛肉", "type": "1群" },
  { "word": "小魚（ししゃも）", "type": "2群" },
  { "word": "ブロッコリー", "type": "3群" },
  { "word": "トマト", "type": "4群" },
  { "word": "ラーメン", "type": "5群" },
  { "word": "ごま油", "type": "6群" },
  { "word": "卵", "type": "1群" },
  { "word": "わかめ", "type": "2群" },
  { "word": "小松菜", "type": "3群" },
  { "word": "梨", "type": "4群" },
  { "word": "もち", "type": "5群" },
  { "word": "ピーナッツ", "type": "6群" },
  { "word": "大豆", "type": "1群" },
  { "word": "のり", "type": "2群" },
  { "word": "ほうれん草", "type": "3群" },
  { "word": "メロン", "type": "4群" },
  { "word": "さつまいも", "type": "5群" },
  { "word": "オリーブオイル", "type": "6群" },
  { "word": "納豆", "type": "1群" },
  { "word": "ひじき", "type": "2群" },
  { "word": "赤ピーマン", "type": "3群" },
  { "word": "みかん", "type": "4群" },
  { "word": "砂糖", "type": "5群" },
  { "word": "マーガリン", "type": "6群" },
  { "word": "豆腐", "type": "1群" },
  { "word": "昆布", "type": "2群" },
  { "word": "にら", "type": "3群" },
  { "word": "ぶどう", "type": "4群" },
  { "word": "うどん", "type": "5群" },
  { "word": "ラード", "type": "6群" }
]



export default wordData; // エクスポートは1回だけ
