//ここのファイルは分類させたい単語(word)と、その分類(type)を下の例に従って入力
// wordData.js
const wordData = [
  { "word": "福岡県", "type": "九州" },
  { "word": "佐賀県", "type": "九州" },
  { "word": "長崎県", "type": "九州" },
  { "word": "大分県", "type": "九州" },
  { "word": "熊本県", "type": "九州" },
  { "word": "宮崎県", "type": "九州" },
  { "word": "鹿児島県", "type": "九州" },
  { "word": "沖縄県", "type": "九州" },
  { "word": "山口県", "type": "中国" },
  { "word": "島根県", "type": "中国" },
  { "word": "広島県", "type": "中国" },
  { "word": "鳥取県", "type": "中国" },
  { "word": "岡山県", "type": "中国" },
  { "word": "愛媛県", "type": "四国" },
  { "word": "香川県", "type": "四国" },
  { "word": "高知県", "type": "四国" },
  { "word": "徳島県", "type": "四国" },
  { "word": "兵庫県", "type": "近畿" },
  { "word": "京都府", "type": "近畿" },
  { "word": "滋賀県", "type": "近畿" },
  { "word": "大阪府", "type": "近畿" },
  { "word": "奈良県", "type": "近畿" },
  { "word": "三重県", "type": "近畿" },
  { "word": "和歌山県", "type": "近畿" },
  { "word": "石川県", "type": "中部" },
  { "word": "福井県", "type": "中部" },
  { "word": "富山県", "type": "中部" },
  { "word": "新潟県", "type": "中部" },
  { "word": "長野県", "type": "中部" },
  { "word": "岐阜県", "type": "中部" },
  { "word": "愛知県", "type": "中部" },
  { "word": "静岡県", "type": "中部" },
  { "word": "山梨県", "type": "中部" },
  { "word": "群馬県", "type": "関東" },
  { "word": "栃木県", "type": "関東" },
  { "word": "茨城県", "type": "関東" },
  { "word": "埼玉県", "type": "関東" },
  { "word": "東京都", "type": "関東" },
  { "word": "神奈川県", "type": "関東" },
  { "word": "千葉県", "type": "関東" },
  { "word": "青森県", "type": "東北" },
  { "word": "岩手県", "type": "東北" },
  { "word": "秋田県", "type": "東北" },
  { "word": "山形県", "type": "東北" },
  { "word": "宮城県", "type": "東北" },
  { "word": "福島県", "type": "東北" },
  { "word": "北海道", "type": "北海道" },
 
]


export default wordData; // エクスポートは1回だけ
