//ここのファイルは分類させたい単語(word)と、その分類(type)を下の例に従って入力
// wordData.js
const wordData = [
  { "word": "福岡市", "type": "九州" },
  { "word": "佐賀市", "type": "九州" },
  { "word": "長崎市", "type": "九州" },
  { "word": "大分市", "type": "九州" },
  { "word": "熊本市", "type": "九州" },
  { "word": "宮崎市", "type": "九州" },
  { "word": "鹿児島市", "type": "九州" },
  { "word": "那覇市", "type": "九州" },
  { "word": "山口市", "type": "中国" },
  { "word": "松江市", "type": "中国" },
  { "word": "広島市", "type": "中国" },
  { "word": "鳥取市", "type": "中国" },
  { "word": "岡山市", "type": "中国" },
  { "word": "松山市", "type": "四国" },
  { "word": "高松市", "type": "四国" },
  { "word": "高知市", "type": "四国" },
  { "word": "徳島市", "type": "四国" },
  { "word": "神戸市", "type": "近畿" },
  { "word": "京都市", "type": "近畿" },
  { "word": "大津市", "type": "近畿" },
  { "word": "大阪市", "type": "近畿" },
  { "word": "奈良市", "type": "近畿" },
  { "word": "津市", "type": "近畿" },
  { "word": "和歌山市", "type": "近畿" },
  { "word": "金沢市", "type": "中部" },
  { "word": "福井市", "type": "中部" },
  { "word": "富山市", "type": "中部" },
  { "word": "新潟市", "type": "中部" },
  { "word": "長野市", "type": "中部" },
  { "word": "岐阜市", "type": "中部" },
  { "word": "名古屋市", "type": "中部" },
  { "word": "静岡市", "type": "中部" },
  { "word": "甲府市", "type": "中部" },
  { "word": "前橋市", "type": "関東" },
  { "word": "宇都宮市", "type": "関東" },
  { "word": "水戸市", "type": "関東" },
  { "word": "さいたま市", "type": "関東" },
  { "word": "東京", "type": "関東" },
  { "word": "横浜市", "type": "関東" },
  { "word": "千葉市", "type": "関東" },
  { "word": "青森市", "type": "東北" },
  { "word": "盛岡市", "type": "東北" },
  { "word": "秋田市", "type": "東北" },
  { "word": "山形市", "type": "東北" },
  { "word": "仙台市", "type": "東北" },
  { "word": "福島市", "type": "東北" },
  { "word": "札幌市", "type": "北海道" },
 
]


export default wordData; // エクスポートは1回だけ
