// wordData.js
const wordData = [
 
  { "word": "の", "type": "助詞" },
  { "word": "が", "type": "助詞" },
  { "word": "に", "type": "助詞" },
  { "word": "と", "type": "助詞" },
  { "word": "は", "type": "助詞" },
  { "word": "も", "type": "助詞" },
  { "word": "で", "type": "助詞" },
  { "word": "から", "type": "助詞" },
  { "word": "より", "type": "助詞" },
  { "word": "へ", "type": "助詞" },
  { "word": "や", "type": "助詞" },
  { "word": "まで", "type": "助詞" },
  { "word": "だけ", "type": "助詞" },
  { "word": "ず", "type": "助詞" },
  { "word": "た", "type": "助動詞" },
  { "word": "だ", "type": "助動詞" },
  { "word": "です", "type": "助動詞" },
  { "word": "ます", "type": "助動詞" },
  { "word": "られる", "type": "助動詞" },
  { "word": "ああ", "type": "感動詞" },
  { "word": "うわあ", "type": "感動詞" },
  { "word": "ええ", "type": "感動詞" },
  { "word": "おお", "type": "感動詞" },
  { "word": "まあ", "type": "感動詞" },
  { "word": "あっ", "type": "感動詞" },
  { "word": "うん", "type": "感動詞" },
  { "word": "こんにちは", "type": "感動詞" },
  { "word": "ばいばい", "type": "感動詞" },
  { "word": "でも", "type": "接続詞" },
  { "word": "だから", "type": "接続詞" },
  { "word": "それに", "type": "接続詞" },
  { "word": "また", "type": "接続詞" },
  { "word": "けれども", "type": "接続詞" },
  { "word": "そして", "type": "接続詞" },
   { "word": "本", "type": "名詞" },
  { "word": "犬", "type": "名詞" },
  { "word": "学校", "type": "名詞" },
  { "word": "勉強", "type": "名詞" },
  { "word": "先生", "type": "名詞" },
  { "word": "友達", "type": "名詞" },
  { "word": "電車", "type": "名詞" },
  { "word": "車", "type": "名詞" },
  { "word": "雨", "type": "名詞" },
  { "word": "雪", "type": "名詞" },
  { "word": "急行列車", "type": "名詞" },
  { "word": "国語", "type": "名詞" },
  { "word": "学生", "type": "名詞" },
  { "word": "神", "type": "名詞" },
  { "word": "卓球", "type": "名詞" },
  { "word": "上", "type": "名詞" },
  { "word": "下", "type": "名詞" },
  { "word": "中", "type": "名詞" },
  { "word": "外", "type": "名詞" },
]



export default wordData; // エクスポートは1回だけ
